#!/usr/bin/env python
# -*- coding: utf8 -*-fr
# pylint: disable=invalid-name
"""
itop-cli is a basic CLI interface for iTop REST interface
"""

__version__ = '1.0'
__authors__ = ['Guillaume Philippon <guillaume.philippon@lal.in2p3.fr>']

from itopapi import ItopapiController, ItopapiConfig
from itopcli import load_configuration_cli, ItopcliConfig, NeedMoreArgs


def main():
    """
    Main function
    """

    ######################
    # Load configuration #
    ######################
    try:
        load_configuration_cli()
    except NeedMoreArgs as e:
        print "Error: {}".format(e.message)
        exit(1)

    ####################
    # Some value check #
    ####################
    if ItopapiConfig.hostname is None \
            or ItopapiConfig.username is None\
            or ItopapiConfig.password is None:
        print "Error: Hostname/Username/Password missing"
        exit(1)

    #####################################
    # Retrieve quattor profile if asked #
    #####################################
    if ItopapiConfig.import_uri is not None:
        if ItopapiConfig.format == 'quattor':
            quattor_controller = ItopapiController()
            quattor_controller.load_from_quattor(ItopapiConfig.import_uri)
            quattor_controller.display()

    #########################
    # Display classes asked #
    #########################
    if ItopcliConfig.classes is not None:
        for itop_class in ItopcliConfig.classes:
            class_controller = ItopapiController()
            if ItopcliConfig.find_instance is None:
                class_controller.load_all(itop_class)
                class_controller.display()
            else:
                for find in ItopcliConfig.find_instance:
                    class_controller.load_one(itop_class, find)
                    class_controller.display()

    if ItopcliConfig.delete_instance is not None:
        class_controller = ItopapiController()
        class_controller.delete_one(ItopcliConfig.delete_instance[0],
                                    ItopcliConfig.delete_instance[1])
        class_controller.display()

if __name__ == "__main__":
    main()
